### ISSUE TITLE
InfluxNamingConventions should allow the tag value "time"

### ISSUE THREAD

**Issue by sfitts** [vert-x3/vertx-micrometer-metrics#100]
### Version

3.8.6

### Context

When attempting to write a tag with the value "time", you get an exception from `InfluxNamingConventions.tagValue`.  This is too restrictive.  The current version (1.7) of Influx allows the use of `time` as a tag value, just not as a tag key.  See https://docs.influxdata.com/influxdb/v1.7/query_language/spec/#keywords.

### Steps to reproduce

Create a meter with a tag value of `time` and attempt to write it via an InfluxMeterRegistry.

**Comment by jotak** [comment]
This sounds like a micrometer issue. Perhaps already solved in newer versions?

**Comment by sfitts** [comment]
You are correct, the class in question does come from micrometer.  But it would be nice if the Vert.x library worked around this by using its own conventions class (the one above is just the default).  FWIW, that's what we've done in our code.

They have not addressed this in the most recent release (just looked at there code in master and it is still the same).

**Comment by sfitts** [comment]
Logged https://github.com/micrometer-metrics/micrometer/issues/1902 to track this on their side.

**Comment by sfitts** [comment]
This has been fixed and will be in `1.1.11`.  What are the update plans here?

**Comment by tsegismont** [comment]
@sfitts have you tried to force the dep version to `1.1.11` in your project? It's a micro release update so it should work.

**Comment by sfitts** [comment]
@tsegismont we're actually using the 1.3.x release without any issues.  I've brought us up to the most current release there to pull in that fix.  Would still be nice to see an update here to a more recent version (the active line is at 1.5.x right now).

**Comment by tsegismont** [comment]
Agreed. Together with @jotak we'll look into upgrading to 1.5.x in Vert.x 4
